import { personalApi, type ExplorationView, type PersonalApi, type PersonalStatus, type ReflectionSession, type SearchView } from "./personal-api";

type Route = "home" | "history" | "detail" | "search" | "sensemaking" | "privacy" | "recovery";
type ExplorationBundle = { session: ReflectionSession; exploration: ExplorationView | null };
const escape = (value: unknown) => String(value ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] ?? c);
const errorText = (error: unknown) => error instanceof Error ? error.message : String(error);
const dateLabel = (value?: string | null) => {
  if (!value) return "Timestamp unavailable";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
};

export async function mountPersonal(api: PersonalApi = personalApi, host: HTMLDivElement = document.querySelector<HTMLDivElement>("#app")!): Promise<void> {
  if (!host) throw new Error("Personal application root is missing");
  let status: PersonalStatus | null = null, sessions: ReflectionSession[] = [], current: ReflectionSession | null = null, exploration: ExplorationView | null = null;
  let route: Route = "home", notice = "", recovery: Record<string, unknown> | null = null, search: SearchView | null = null, sensemaking: ExplorationBundle[] | null = null, busy = false;
  const ordered = () => [...sessions].sort((a, b) => String(b.updated_at ?? b.created_at ?? "").localeCompare(String(a.updated_at ?? a.created_at ?? "")));
  const refresh = async () => { const nextStatus = await api.status(); status = nextStatus; if (!nextStatus.locked && nextStatus.local_personal === "ADMITTED") { sessions = (await api.reflectionList()).sessions; sensemaking = null; } return nextStatus; };
  const open = async (id: string) => { current = await api.reflectionGet(id); exploration = await api.explorationGet(id); route = "detail"; render(); };
  const loadSensemaking = async () => {
    if (sensemaking) return sensemaking;
    sensemaking = await Promise.all(ordered().map(async (session) => {
      try { return { session, exploration: await api.explorationGet(session.session_id) }; }
      catch { return { session, exploration: null }; }
    }));
    return sensemaking;
  };
  const act = async (action: () => Promise<void>) => { busy = true; try { await action(); } catch (error) { notice = `Operation error: ${errorText(error)}`; } finally { busy = false; render(); } };
  const nav = () => `<nav class="product-nav" aria-label="Personal navigation"><button data-route="home">Home</button><button data-route="history">History</button><button data-route="search">Search</button><button data-route="sensemaking">Understand</button><button data-route="privacy">Privacy & local status</button><button data-route="recovery">Backup & recovery</button><button id="lock">Lock vault</button></nav>`;
  const sessionRow = (item: ReflectionSession) => `<article class="session-row"><button data-open="${escape(item.session_id)}">${item.state === "ACTIVE" ? "Resume" : "Read"}</button><strong>${escape(item.title)}</strong><span>${item.state}</span><small>${item.turn_count} entries · ${escape(dateLabel(item.updated_at ?? item.created_at))}</small></article>`;
  const noticeMarkup = () => `<p class="result" role="status">${escape(busy ? "Working…" : notice)}</p>`;
  const bindCommon = () => {
    host.querySelectorAll<HTMLButtonElement>("[data-route]").forEach((button) => button.addEventListener("click", () => void act(async () => { route = button.dataset.route as Route; notice = ""; if (route === "sensemaking" || route === "home") await loadSensemaking(); })));
    host.querySelector("#lock")?.addEventListener("click", () => void act(async () => { await api.lock(); await refresh(); notice = "Vault locked."; }));
    host.querySelectorAll<HTMLButtonElement>("[data-open]").forEach((button) => button.addEventListener("click", () => void act(() => open(button.dataset.open!))));
  };
  const submit = (selector: string, action: () => Promise<void>) => host.querySelector<HTMLFormElement>(selector)?.addEventListener("submit", (event) => { event.preventDefault(); void act(action); });

  const explorationMarkup = () => {
    if (!current || !exploration) return "";
    const question = exploration.next_question;
    const formulations = exploration.formulations.map((item) => `<article class="derived"><h4>Working formulation · ${escape(item.status)}</h4><p>${escape(item.summary)}</p><p>Derived content is a proposal, not a USER statement or established fact.</p>${item.correction_text ? `<p>Correction: ${escape(item.correction_text)}</p>` : ""}${item.status === "PROPOSED" ? `<form data-correct="${escape(item.formulation_id)}"><label>Correction <textarea required maxlength="12000"></textarea></label><button>Save correction</button></form><button data-accept="${escape(item.formulation_id)}">Accept formulation</button><button data-reject="${escape(item.formulation_id)}">Reject formulation</button>` : ""}</article>`).join("");
    return `<section class="guided-exploration"><h3>Guided exploration</h3>${question ? `<article><h4>Current question</h4><p>${escape(question.text)}</p><form id="answer-question"><label>Your answer <textarea id="question-answer" required maxlength="12000"></textarea></label><button>Answer</button><button type="button" id="skip-question">Skip</button></form></article>` : "<p>No current question.</p>"}<button id="start-exploration">${exploration.snapshots.length ? "Refresh exploration" : "Start exploration"}</button><button id="propose-formulation">Propose working formulation</button>${formulations}</section>`;
  };
  const detailMarkup = () => {
    if (!current) return "";
    const turns = [...(current.turns ?? [])].sort((a, b) => a.sequence - b.sequence);
    return `<main class="product-shell">${nav()}<header class="session-header"><p>REFLECTION</p><h1>${escape(current.title)}</h1><p>${current.state === "CLOSED" ? "Closed — read only" : "Active — you can continue writing"}</p><button data-route="history">Back to history</button></header><section class="card"><h2>Your entries</h2>${turns.length ? turns.map((turn) => `<article class="session-turn"><strong>USER · entry ${turn.sequence}</strong><small>${escape(dateLabel(turn.created_at))}</small><p>${escape(turn.content)}</p></article>`).join("") : "<p>No entries yet.</p>"}${current.state === "ACTIVE" ? `<form id="add-turn"><label>Your text <textarea id="reflection-turn" required maxlength="12000"></textarea></label><button class="primary">Save entry</button></form><button id="close-reflection">Close reflection</button>` : ""}<button id="delete-reflection" class="danger">Delete reflection</button></section>${explorationMarkup()}${noticeMarkup()}</main>`;
  };
  const homeMarkup = () => {
    const recent = ordered().slice(0, 5);
    const bundles = sensemaking ?? [];
    const active = ordered().filter((item) => item.state === "ACTIVE");
    const unknowns = bundles.reduce((count, bundle) => count + (bundle.exploration?.context.filter((item) => item.kind === "UNKNOWN").length ?? 0), 0);
    const contradictions = bundles.reduce((count, bundle) => count + (bundle.exploration?.context.filter((item) => item.kind === "CONTRADICTION").length ?? 0), 0);
    const current = bundles.reduce((count, bundle) => count + (bundle.exploration?.formulations.filter((item) => item.status === "CURRENT").length ?? 0), 0);
    return `<main class="product-shell">${nav()}<section class="product-home"><p>PERSONAL HOME</p><h1>A quiet place to return to.</h1><p>Local Personal Mode. Real Data Gate: CLOSED.</p></section><div class="status-strip"><div><span>VAULT</span><strong>Unlocked</strong></div><div><span>PERSONAL</span><strong>${escape(status?.local_personal ?? "UNKNOWN")}</strong></div><div><span>REFLECTIONS</span><strong>${sessions.length} saved</strong></div><div><span>RECOVERY</span><strong>${recovery ? escape(String(recovery.rotation ?? "Status available")) : "Check status"}</strong></div></div><section class="card daily-review"><p>DAILY REVIEW</p><h2>What is active</h2><p>This is a local summary of existing reflections and derived exploration—not a recommendation or priority ranking.</p><div class="review-counts"><span><strong>${active.length}</strong> active reflections</span><span><strong>${unknowns}</strong> unresolved unknowns</span><span><strong>${contradictions}</strong> contradictions</span><span><strong>${current}</strong> current working formulations</span></div>${active.length ? active.slice(0, 3).map(sessionRow).join("") : "<p>No active reflections to continue.</p>"}<button data-route="sensemaking">Open Understand</button></section><div class="grid"><section class="card"><p>QUICK CAPTURE</p><h2>Save a thought</h2><form id="quick-capture-form"><label>Optional title <input id="quick-capture-title" maxlength="160" placeholder="Quick capture" autofocus /></label><label>Your text <textarea id="quick-capture-text" required maxlength="12000" placeholder="Write what you want to remember…"></textarea></label><button class="primary">Save capture</button></form></section><section class="card"><p>RECENT</p><h2>Continue</h2>${recent.length ? recent.map(sessionRow).join("") : "<p>No saved reflections yet. Your first capture will appear here.</p>"}<button data-route="history">View full history</button></section><section class="card"><p>TRUSTED BACKUP</p><h2>Keep a recovery copy</h2><p>Backups are encrypted locally. Restore always creates an isolated candidate, never overwrites this vault.</p><button data-route="recovery">Backup & recovery</button></section></div>${noticeMarkup()}</main>`;
  };
  const historyMarkup = () => `<main class="product-shell">${nav()}<section class="product-home"><p>PERSONAL HISTORY</p><h1>Your saved reflections</h1><p>Newest saved activity first. Active reflections can be resumed; closed reflections are read-only.</p></section><section class="card sessions-card">${ordered().length ? ordered().map(sessionRow).join("") : "<p>No history yet. Save a quick capture on Home to begin.</p>"}</section>${noticeMarkup()}</main>`;
  const searchMarkup = () => `<main class="product-shell">${nav()}<section class="product-home"><p>SEARCH</p><h1>Find your saved words</h1></section><section class="card"><form id="search-form"><label>Words from a title or USER entry <input id="search-query" required value="${escape(search?.query ?? "")}" /></label><label>State <select id="search-state"><option value="ALL">All</option><option value="ACTIVE">Active</option><option value="CLOSED">Closed</option></select></label><button class="primary">Search</button></form>${search ? `<p>${search.total_matches ? `${search.total_matches} match(es)` : "No reflections matched those words."}</p>${search.results.map((item) => `<article class="search-result"><button data-open="${escape(item.session_id)}">Open reflection</button><strong>${escape(item.session_title)}</strong><span>${escape(item.session_state)}</span><p>${escape(item.excerpt)}</p></article>`).join("")}` : "<p>Search saved USER text and reflection titles.</p>"}</section>${noticeMarkup()}</main>`;
  const source = (bundle: ExplorationBundle) => `<small>Derived from reflection: ${escape(bundle.session.title)} · <button class="link-button" data-open="${escape(bundle.session.session_id)}">Open source reflection</button></small>`;
  const derivedCard = (bundle: ExplorationBundle, text: string, detail = "") => `<article class="derived"><p>DERIVED · exploration output</p><p>${escape(text)}</p>${detail ? `<small>${escape(detail)}</small>` : ""}${source(bundle)}</article>`;
  const senseSection = (title: string, content: string, empty: string) => `<section class="sense-section"><h2>${title}</h2>${content || `<p>${empty}</p>`}</section>`;
  const sensemakingMarkup = () => {
    const bundles = sensemaking ?? [];
    const withExploration = bundles.filter((bundle) => bundle.exploration);
    const context = (kind: "KNOWN" | "UNKNOWN" | "CONTRADICTION") => withExploration.flatMap((bundle) => bundle.exploration!.context.filter((item) => item.kind === kind).map((item) => derivedCard(bundle, item.text, `${kind} · ${item.state}`))).join("");
    const hypotheses = withExploration.flatMap((bundle) => bundle.exploration!.hypotheses.map((item) => derivedCard(bundle, item.proposal_text, `Hypothesis · uncertainty: ${item.uncertainty_text} · discriminator: ${item.discriminator_text}`))).join("");
    const formulations = withExploration.flatMap((bundle) => bundle.exploration!.formulations.map((item) => derivedCard(bundle, item.summary, `Working formulation v${item.version} · ${item.status}${item.correction_text ? ` · correction: ${item.correction_text}` : ""}`))).join("");
    const current = withExploration.flatMap((bundle) => bundle.exploration!.formulations.filter((item) => item.status === "CURRENT").map((item) => derivedCard(bundle, item.summary, `Current working formulation v${item.version}`))).join("");
    const untouched = bundles.filter((bundle) => !bundle.exploration || (!(bundle.exploration.context.length || bundle.exploration.hypotheses.length || bundle.exploration.formulations.length || bundle.exploration.next_question))).map((bundle) => `<li>${escape(bundle.session.title)} · no exploration has been recorded yet.</li>`).join("");
    return `<main class="product-shell">${nav()}<section class="product-home"><p>SENSEMAKING</p><h1>Understand what is present.</h1><p>This view groups existing exploration output from saved reflections. It does not create a global truth: every item remains derived and linked to its source.</p></section><div class="sensemaking">${senseSection("Current picture", current, "No current working formulations have been accepted yet.")}${senseSection("Known context", context("KNOWN"), "No derived known-context items yet.")}${senseSection("Unknowns", context("UNKNOWN"), "No unknowns are currently recorded.")}${senseSection("Contradictions", context("CONTRADICTION"), "No contradictions are currently recorded.")}${senseSection("Hypotheses", hypotheses, "No hypotheses have been proposed.")}${senseSection("Working formulations", formulations, "No working formulations have been proposed.")}<section class="sense-section"><h2>Reflections without exploration</h2>${untouched ? `<ul>${untouched}</ul>` : "<p>Every saved reflection currently has exploration information, or there are no saved reflections.</p>"}</section></div>${noticeMarkup()}</main>`;
  };
  const privacyMarkup = () => `<main class="product-shell">${nav()}<section class="product-home"><p>PRIVACY & LOCAL STATUS</p><h1>Your local Personal mode.</h1><p>These are the states currently reported by this Personal runtime; they are not broader guarantees.</p></section><div class="grid"><section class="card"><p>RUNTIME</p><h2>Local operation</h2><dl><dt>Profile</dt><dd>${escape(status?.runtime_profile)}</dd><dt>Processing</dt><dd>${escape(status?.privacy?.core_processing_location)}</dd><dt>Network</dt><dd>${escape(status?.network)}</dd><dt>Inbound listener</dt><dd>${escape(status?.inbound_listener)}</dd><dt>Provider</dt><dd>${escape(status?.outbound_provider)}</dd></dl></section><section class="card"><p>DATA CONTROL</p><h2>Personal admission</h2><dl><dt>REAL_DATA_GATE</dt><dd>${escape(status?.real_data_gate)}</dd><dt>Personal admission</dt><dd>${escape(status?.local_personal)}</dd><dt>Vault</dt><dd>${status?.locked ? "Locked" : "Unlocked"}</dd><dt>Cloud storage</dt><dd>${escape(status?.privacy?.cloud_storage)}</dd><dt>Cloud disclosure</dt><dd>${escape(status?.privacy?.cloud_disclosure)}</dd><dt>Telemetry</dt><dd>${escape(status?.privacy?.telemetry)}</dd></dl></section><section class="card"><p>OWNER CONTROLS</p><h2>Recovery & export</h2><p>Backup and recovery status is available from the existing local recovery service. OWNER_ONLY export is created from the same local area.</p><button data-route="recovery" class="primary">Backup & recovery</button><button data-route="recovery">OWNER_ONLY export</button></section></div>${noticeMarkup()}</main>`;
  const recoveryMarkup = () => `<main class="product-shell">${nav()}<section class="product-home"><p>TRUSTED BACKUP & RECOVERY</p><h1>Keep your local vault recoverable.</h1><p>These operations use the existing local Personal recovery service. They do not change the active vault.</p></section><div class="grid"><section class="card"><p>STATUS</p><h2>Recovery readiness</h2><p>${recovery ? `Personal admission: ${escape(String(recovery.local_personal ?? "Unavailable"))}. Rotation: ${escape(String(recovery.rotation ?? "Unavailable"))}.` : "Status has not been checked in this view."}</p><button id="recovery-status">Refresh status</button></section><section class="card"><p>ENCRYPTED BACKUP</p><h2>Create backup</h2><p>Create an encrypted backup of the current Personal vault. The returned identifier can be used for isolated restore.</p><form id="backup-form"><label>Recovery secret <input id="backup-secret" type="password" required /></label><button class="primary">Create encrypted backup</button></form></section><section class="card"><p>OWNER ONLY</p><h2>Export</h2><p>Create an encrypted export for the owner only.</p><form id="export-form"><label>Recovery secret <input id="export-secret" type="password" required /></label><button>Create owner-only export</button></form></section></div><section class="card"><p>ISOLATED RESTORE</p><h2>Verify a backup without changing this vault</h2><p>Restore creates a separate candidate. It never overwrites the active vault.</p><form id="restore-form"><label>Backup identifier <input id="restore-backup-id" required /></label><label>Recovery secret <input id="restore-secret" type="password" required /></label><button>Restore to isolated candidate</button></form></section>${noticeMarkup()}</main>`;

  function render() {
    if (!status) { host.innerHTML = "<main><p>Loading Personal vault state…</p></main>"; return; }
    if (status.local_personal === "NOT_ADMITTED") { host.innerHTML = `<main class="unlock"><h1>Personal Home</h1><p>Personal vault is not admitted on this device. REAL_DATA_GATE remains CLOSED.</p>${noticeMarkup()}</main>`; return; }
    if (status.locked) { host.innerHTML = `<main class="unlock"><p>PERSONAL HOME</p><h1>Vault locked</h1><p>Unlock to use your local reflections, history, and recovery actions. REAL_DATA_GATE remains CLOSED.</p><form id="unlock-form"><label>Unlock secret <input id="unlock-secret" type="password" required autofocus /></label><button class="primary">Unlock</button></form>${noticeMarkup()}</main>`; submit("#unlock-form", async () => { await api.unlock(host.querySelector<HTMLInputElement>("#unlock-secret")!.value); await refresh(); await loadSensemaking(); notice = "Vault unlocked."; }); return; }
    host.innerHTML = route === "detail" ? detailMarkup() : route === "history" ? historyMarkup() : route === "search" ? searchMarkup() : route === "sensemaking" ? sensemakingMarkup() : route === "privacy" ? privacyMarkup() : route === "recovery" ? recoveryMarkup() : homeMarkup();
    bindCommon();
    submit("#quick-capture-form", async () => { const text = host.querySelector<HTMLTextAreaElement>("#quick-capture-text")!.value.trim(); if (!text) return; const title = host.querySelector<HTMLInputElement>("#quick-capture-title")!.value.trim() || "Quick capture"; const created = await api.reflectionCreate(title); await api.reflectionAddTurn(created.session_id, text); await refresh(); await loadSensemaking(); route = "home"; notice = "Capture saved to your history."; });
    submit("#search-form", async () => { const query = host.querySelector<HTMLInputElement>("#search-query")!.value.trim(); if (!query) return; search = await api.reflectionSearch(query, host.querySelector<HTMLSelectElement>("#search-state")!.value as "ALL" | "ACTIVE" | "CLOSED", 20, 0); });
    host.querySelector("#recovery-status")?.addEventListener("click", () => void act(async () => { recovery = await api.personalRecoveryStatus() as Record<string, unknown>; notice = "Recovery status refreshed."; }));
    submit("#backup-form", async () => { if (!window.confirm("Create an encrypted backup of the current Personal vault?")) return; const value = await api.personalBackup(host.querySelector<HTMLInputElement>("#backup-secret")!.value) as { backup_id?: string }; notice = value.backup_id ? `Encrypted backup created. Backup identifier: ${value.backup_id}` : "Encrypted backup created."; });
    submit("#export-form", async () => { if (!window.confirm("Create an OWNER_ONLY encrypted export?")) return; const value = await api.personalExportOwner(host.querySelector<HTMLInputElement>("#export-secret")!.value) as { export_id?: string; audience?: string }; notice = `Owner-only export created${value.export_id ? `. Export identifier: ${value.export_id}` : ""}${value.audience ? ` (${value.audience})` : ""}.`; });
    submit("#restore-form", async () => { if (!window.confirm("Restore this backup to an isolated candidate? The active vault will not be overwritten.")) return; const value = await api.personalRestoreIsolated(host.querySelector<HTMLInputElement>("#restore-backup-id")!.value, host.querySelector<HTMLInputElement>("#restore-secret")!.value) as { candidate_id?: string }; notice = value.candidate_id ? `Isolated restore candidate created: ${value.candidate_id}` : "Isolated restore candidate created."; });
    if (route === "detail") bindDetail();
  }
  function bindDetail() {
    host.querySelector("#close-reflection")?.addEventListener("click", () => { if (current) void act(async () => { await api.reflectionClose(current!.session_id); await open(current!.session_id); }); });
    host.querySelector("#delete-reflection")?.addEventListener("click", () => { if (current && window.confirm("Delete this reflection and all of its entries? This cannot be undone.")) void act(async () => { await api.reflectionDelete(current!.session_id); current = null; route = "history"; await refresh(); notice = "Reflection deleted."; }); });
    submit("#add-turn", async () => { const text = host.querySelector<HTMLTextAreaElement>("#reflection-turn")!.value.trim(); if (text && current) { await api.reflectionAddTurn(current.session_id, text); await open(current.session_id); } });
    host.querySelector("#start-exploration")?.addEventListener("click", () => { if (current) void act(async () => { exploration = await api.explorationStart(current!.session_id); }); });
    host.querySelector("#propose-formulation")?.addEventListener("click", () => { if (current) void act(async () => { await api.formulationPropose(current!.session_id); await open(current!.session_id); }); });
    submit("#answer-question", async () => { const question = exploration?.next_question, answer = host.querySelector<HTMLTextAreaElement>("#question-answer")!.value.trim(); if (question && answer) exploration = await api.explorationAnswer(question.question_id, answer); });
    host.querySelector("#skip-question")?.addEventListener("click", () => { const question = exploration?.next_question; if (question) void act(async () => { exploration = await api.explorationSkip(question.question_id); }); });
    host.querySelectorAll<HTMLFormElement>("[data-correct]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const text = form.querySelector<HTMLTextAreaElement>("textarea")!.value.trim(); if (text) void act(async () => { await api.formulationCorrect(form.dataset.correct!, text); await open(current!.session_id); }); }));
    host.querySelectorAll<HTMLButtonElement>("[data-accept]").forEach((button) => button.addEventListener("click", () => void act(async () => { await api.formulationAccept(button.dataset.accept!); await open(current!.session_id); })));
    host.querySelectorAll<HTMLButtonElement>("[data-reject]").forEach((button) => button.addEventListener("click", () => void act(async () => { await api.formulationReject(button.dataset.reject!); await open(current!.session_id); })));
  }
  render();
  try { const currentStatus = await refresh(); if (!currentStatus.locked) await loadSensemaking(); render(); } catch (error) { status = { runtime_profile: "LOCAL_PERSONAL", real_data_gate: "CLOSED", local_personal: "ADMISSION_AVAILABLE", locked: true, inbound_listener: "NONE", outbound_provider: "NOT_CONFIGURED", network: "OFFLINE_NO_LISTENER", privacy: { core_processing_location: "LOCAL", cloud_storage: "DISABLED", cloud_disclosure: "NEVER_CLOUD", telemetry: "OFF" } }; notice = `Operation error: ${errorText(error)}`; render(); }
}

if (document.querySelector("#app")) void mountPersonal();
