import { personalApi, type ExplorationView, type PersonalApi, type PersonalStatus, type ReflectionSession, type SearchView } from "./personal-api";

const escape = (value: unknown) => String(value ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c] ?? c);
const errorText = (error: unknown) => error instanceof Error ? error.message : String(error);

export async function mountPersonal(api: PersonalApi = personalApi, host: HTMLDivElement = document.querySelector<HTMLDivElement>("#app")!): Promise<void> {
  if (!host) throw new Error("Personal application root is missing");
  let status: PersonalStatus | null = null, sessions: ReflectionSession[] = [], current: ReflectionSession | null = null, exploration: ExplorationView | null = null, notice = "";
  let route: "list" | "new" | "detail" | "search" = "list";
  const setNotice = (value: string) => { notice = value; render(); };
  const refresh = async () => { status = await api.status(); if (!status.locked && status.local_personal === "ADMITTED") sessions = (await api.reflectionList()).sessions; };
  const open = async (id: string) => { current = await api.reflectionGet(id); exploration = await api.explorationGet(id); route = "detail"; render(); };
  const submit = (selector: string, action: () => Promise<void>) => host.querySelector<HTMLFormElement>(selector)?.addEventListener("submit", (event) => { event.preventDefault(); void action().catch((error) => setNotice(errorText(error))); });

  const explorationMarkup = () => {
    if (!current || !exploration) return "";
    const q = exploration.next_question;
    const forms = exploration.formulations.map((item) => `<article class="derived"><h4>Working formulation · ${escape(item.status)}</h4><p>${escape(item.summary)}</p>${item.correction_text ? `<p>Correction: ${escape(item.correction_text)}</p>` : ""}${item.status === "PROPOSED" ? `<form data-correct="${escape(item.formulation_id)}"><label>Correction <textarea required maxlength="12000"></textarea></label><button>Save correction</button></form><button data-accept="${escape(item.formulation_id)}">Accept formulation</button><button data-reject="${escape(item.formulation_id)}">Reject formulation</button>` : ""}</article>`).join("");
    return `<section class="exploration"><h3>Guided exploration</h3><p>Derived prompts and working formulations are not original user statements or established facts.</p>${q ? `<article><h4>Current question</h4><p>${escape(q.text)}</p><form id="answer-question"><label>Your answer <textarea id="question-answer" required maxlength="12000"></textarea></label><button>Answer</button><button type="button" id="skip-question">Skip</button></form></article>` : "<p>No current question.</p>"}<button id="start-exploration">${exploration.snapshots.length ? "Refresh exploration" : "Start exploration"}</button><button id="propose-formulation">Propose working formulation</button>${exploration.context.length ? `<h4>Context to examine</h4><ul>${exploration.context.map((item) => `<li>${escape(item.kind)}: ${escape(item.text)} (${escape(item.state)})</li>`).join("")}</ul>` : ""}${forms}</section>`;
  };
  const detailMarkup = () => {
    if (!current) return "";
    const turns = [...(current.turns ?? [])].sort((a, b) => a.sequence - b.sequence);
    return `<main><header><h1>${escape(current.title)}</h1><p>Personal vault · REAL_DATA_GATE: CLOSED · ${current.state === "CLOSED" ? "Closed — read only" : "Active"}</p><button id="back">All reflections</button></header><section><h2>Your entries</h2>${turns.length ? turns.map((turn) => `<article class="user-turn" data-turn-id="${escape(turn.turn_id)}"><h3>Your text · entry ${turn.sequence}</h3><p>${escape(turn.content)}</p></article>`).join("") : "<p>No entries yet. Write a first note below.</p>"}${current.state === "ACTIVE" ? `<form id="add-turn"><label>Your text <textarea id="reflection-turn" required maxlength="12000"></textarea></label><button>Add entry</button></form><button id="close-reflection">Close reflection</button>` : ""}<button id="delete-reflection" class="danger">Delete reflection</button></section>${explorationMarkup()}<p role="status">${escape(notice)}</p></main>`;
  };
  const searchMarkup = (view?: SearchView) => `<main><header><h1>Search reflections</h1><button id="back">All reflections</button></header><form id="search-form"><label>Words from your entries <input id="search-query" required value="${escape(view?.query ?? "")}" /></label><label>State <select id="search-state"><option value="ALL">All</option><option value="ACTIVE">Active</option><option value="CLOSED">Closed</option></select></label><button>Search</button></form>${view ? `<p>${view.total_matches ? `${view.total_matches} match(es)` : "No reflections matched those words."}${view.truncated || view.has_more ? " Results are bounded; refine the search to see more." : ""}</p><ul>${view.results.map((item) => `<li class="search-result"><button data-open="${escape(item.session_id)}">Open reflection</button> <strong>${escape(item.session_title)}</strong> · ${escape(item.session_state)}<p>${escape(item.excerpt)}</p></li>`).join("")}</ul>` : "<p>Search saved USER text and reflection titles.</p>"}<p role="status">${escape(notice)}</p></main>`;

  function render() {
    if (!status) { host.innerHTML = "<main><p>Loading Personal vault state…</p></main>"; return; }
    if (status.local_personal === "NOT_ADMITTED") { host.innerHTML = `<main><h1>Personal Reflection Workspace</h1><p>Personal vault is not admitted on this device. REAL_DATA_GATE remains CLOSED.</p><p role="status">${escape(notice)}</p></main>`; return; }
    if (status.locked) { host.innerHTML = `<main><h1>Personal Reflection Workspace</h1><p>Vault is locked. REAL_DATA_GATE remains CLOSED.</p><form id="unlock-form"><label>Unlock secret <input id="unlock-secret" type="password" required /></label><button>Unlock</button></form><p role="status">${escape(notice)}</p></main>`; submit("#unlock-form", async () => { await api.unlock(host.querySelector<HTMLInputElement>("#unlock-secret")!.value); await refresh(); notice = "Vault unlocked."; render(); }); return; }
    if (route === "detail") { host.innerHTML = detailMarkup(); bindDetail(); return; }
    if (route === "search") { host.innerHTML = searchMarkup(); bindSearch(); return; }
    host.innerHTML = `<main><header><h1>Personal Reflection Workspace</h1><p>Vault unlocked · Personal local workspace · REAL_DATA_GATE: CLOSED</p><button id="lock">Lock vault</button><button id="new-reflection">New reflection</button><button id="search-reflections">Search</button></header>${route === "new" ? `<section><h2>New reflection</h2><form id="create-reflection"><label>Title <input id="reflection-title" maxlength="160" placeholder="A short label (optional)" /></label><label>Quick capture <textarea id="quick-capture" required maxlength="12000"></textarea></label><button>Create and save entry</button><button type="button" id="cancel-new">Cancel</button></form></section>` : `<section><h2>Recent reflections</h2>${sessions.length ? `<ul>${sessions.map((item) => `<li><button data-open="${escape(item.session_id)}">Open</button> <strong>${escape(item.title)}</strong> · ${escape(item.state)} · ${item.turn_count} entries</li>`).join("")}</ul>` : "<p>No reflections yet. Create one to save a first note.</p>"}</section>`}<p role="status">${escape(notice)}</p></main>`;
    host.querySelector("#lock")?.addEventListener("click", () => void api.lock().then(async () => { await refresh(); render(); }).catch((error) => setNotice(errorText(error))));
    host.querySelector("#new-reflection")?.addEventListener("click", () => { route = "new"; render(); }); host.querySelector("#search-reflections")?.addEventListener("click", () => { route = "search"; render(); }); host.querySelector("#cancel-new")?.addEventListener("click", () => { route = "list"; render(); });
    host.querySelectorAll<HTMLButtonElement>("[data-open]").forEach((button) => button.addEventListener("click", () => void open(button.dataset.open!).catch((error) => setNotice(errorText(error)))));
    submit("#create-reflection", async () => { const title = host.querySelector<HTMLInputElement>("#reflection-title")!.value.trim() || "Untitled reflection"; const text = host.querySelector<HTMLTextAreaElement>("#quick-capture")!.value.trim(); if (!text) return; const created = await api.reflectionCreate(title); await api.reflectionAddTurn(created.session_id, text); await refresh(); await open(created.session_id); });
  }
  function bindSearch() { host.querySelector("#back")?.addEventListener("click", () => { route = "list"; render(); }); submit("#search-form", async () => { const query = host.querySelector<HTMLInputElement>("#search-query")!.value.trim(), state = host.querySelector<HTMLSelectElement>("#search-state")!.value as "ALL" | "ACTIVE" | "CLOSED"; if (!query) return; host.innerHTML = searchMarkup(await api.reflectionSearch(query, state, 20, 0)); bindSearch(); }); host.querySelectorAll<HTMLButtonElement>("[data-open]").forEach((button) => button.addEventListener("click", () => void open(button.dataset.open!).catch((error) => setNotice(errorText(error))))); }
  function bindDetail() {
    host.querySelector("#back")?.addEventListener("click", () => { route = "list"; current = null; exploration = null; void refresh().then(render); });
    submit("#add-turn", async () => { const text = host.querySelector<HTMLTextAreaElement>("#reflection-turn")!.value.trim(); if (!text || !current) return; await api.reflectionAddTurn(current.session_id, text); await open(current.session_id); });
    host.querySelector("#close-reflection")?.addEventListener("click", () => { if (current) void api.reflectionClose(current.session_id).then(() => open(current!.session_id)).catch((error) => setNotice(errorText(error))); });
    host.querySelector("#delete-reflection")?.addEventListener("click", () => { if (current && window.confirm("Delete this reflection and all of its entries? This cannot be undone.")) void api.reflectionDelete(current.session_id).then(async () => { current = null; route = "list"; await refresh(); render(); }).catch((error) => setNotice(errorText(error))); });
    host.querySelector("#start-exploration")?.addEventListener("click", () => { if (current) void api.explorationStart(current.session_id).then((value) => { exploration = value; render(); }).catch((error) => setNotice(errorText(error))); }); host.querySelector("#propose-formulation")?.addEventListener("click", () => { if (current) void api.formulationPropose(current.session_id).then(() => open(current!.session_id)).catch((error) => setNotice(errorText(error))); });
    submit("#answer-question", async () => { const q = exploration?.next_question, answer = host.querySelector<HTMLTextAreaElement>("#question-answer")!.value.trim(); if (q && answer) { exploration = await api.explorationAnswer(q.question_id, answer); render(); } }); host.querySelector("#skip-question")?.addEventListener("click", () => { const q = exploration?.next_question; if (q) void api.explorationSkip(q.question_id).then((value) => { exploration = value; render(); }).catch((error) => setNotice(errorText(error))); });
    host.querySelectorAll<HTMLFormElement>("[data-correct]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const text = form.querySelector<HTMLTextAreaElement>("textarea")!.value.trim(); if (text) void api.formulationCorrect(form.dataset.correct!, text).then(() => open(current!.session_id)).catch((error) => setNotice(errorText(error))); })); host.querySelectorAll<HTMLButtonElement>("[data-accept]").forEach((button) => button.addEventListener("click", () => void api.formulationAccept(button.dataset.accept!).then(() => open(current!.session_id)).catch((error) => setNotice(errorText(error))))); host.querySelectorAll<HTMLButtonElement>("[data-reject]").forEach((button) => button.addEventListener("click", () => void api.formulationReject(button.dataset.reject!).then(() => open(current!.session_id)).catch((error) => setNotice(errorText(error)))));
  }
  render();
  try { await refresh(); render(); } catch (error) { status = { data_mode: "LOCAL_PERSONAL", real_data_gate: "CLOSED", local_personal: "ADMISSION_AVAILABLE", locked: true }; notice = `Operation error: ${errorText(error)}`; render(); }
}

if (document.querySelector("#app")) void mountPersonal();
